import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Clock3, Maximize, MonitorUp, RefreshCw, Stethoscope } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const statusLabel: Record<string, string> = { scheduled: "待报到", checked_in: "候诊中", called: "请前往治疗区", completed: "已完成", no_show: "爽约" };
export default function BoardPage() {
  const board = trpc.board.today.useQuery(undefined, { refetchInterval: 10_000 });
  const [full, setFull] = useState(false);
  const queue = board.data ?? [];
  const active = queue.find(item => item.status === "called") ?? queue.find(item => item.status === "checked_in");
  const checkedIn = queue.filter(item => ["checked_in", "called"].includes(item.status));
  const waiting = queue.filter(item => item.status === "scheduled");
  const fullScreen = () => { if (!document.fullscreenElement) { document.documentElement.requestFullscreen(); setFull(true); } else { document.exitFullscreen(); setFull(false); } };
  const smallList = (items: typeof queue, empty: string) => items.length ? <div className="divide-y divide-white/10">{items.slice(0, 5).map(item => <div key={item.id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-lg">{item.sequence} · {item.patientName}</p><p className="mt-1 text-sm text-[#a8c7bf]">{item.projectName} · {item.scheduledAt.toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })}</p></div><p className="text-sm text-[#e5c57f]">{statusLabel[item.status]}</p></div>)}</div> : <p className="py-9 text-center text-sm text-[#a7c5bd]">{empty}</p>;
  return <div className="min-h-screen bg-[#0d3030] text-white p-5 md:p-10 clinic-grid"><header className="flex items-center justify-between border-b border-white/15 pb-5"><div className="flex items-center gap-3"><span className="h-11 w-11 rounded-2xl bg-[#d1a85e] grid place-items-center"><Stethoscope className="h-5 w-5 text-[#123f3d]" /></span><div><p className="font-serif text-xl">疼痛门诊候诊中心</p><p className="mt-1 text-xs text-[#9abeb5] tracking-[0.12em]">TREATMENT WAITING BOARD</p></div></div><div className="flex items-center gap-2"><span className="hidden sm:flex items-center gap-2 text-sm text-[#a9c8c0]"><Clock3 className="h-4 w-4" />{new Date().toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })}</span><Button size="icon" variant="ghost" className="text-white hover:bg-white/10" onClick={() => board.refetch()}><RefreshCw className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="text-white hover:bg-white/10" onClick={fullScreen}><Maximize className="h-4 w-4" /></Button></div></header><main className="mt-7 grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><section className="rounded-[2rem] bg-[#d9af65] p-7 text-[#173e3b] flex flex-col min-h-[290px]"><p className="text-xs font-semibold tracking-[0.16em] text-[#705321]">NOW SERVING</p>{active ? <><p className="mt-8 text-6xl sm:text-7xl font-serif">{active.sequence}</p><p className="mt-4 text-2xl font-serif">{active.patientName}</p><p className="mt-2 text-[#5e4a26]">{active.projectName}</p><p className="mt-auto flex items-center gap-2 text-sm"><MonitorUp className="h-4 w-4" />{active.status === "called" ? "请前往治疗区" : "请在候诊区等候"}</p></> : <><p className="mt-10 text-3xl font-serif">暂无叫号</p><p className="mt-3 text-[#5e4a26]">请留意屏幕信息。</p></>}</section><section className="rounded-[2rem] border border-white/12 bg-[#123d3c]/80 p-5 sm:p-7"><div className="flex items-center justify-between"><h2 className="font-serif text-2xl">已报到候诊</h2><p className="text-sm text-[#a4c5bc]">每 10 秒自动更新</p></div>{board.isLoading ? <p className="py-16 text-center text-[#a7c5bd]">正在载入队列…</p> : smallList(checkedIn, "当前暂无已报到候诊患者。")}</section></main><section className="mt-6 rounded-[2rem] border border-white/12 bg-[#123d3c]/65 p-5 sm:p-7"><div className="flex items-center justify-between"><h2 className="font-serif text-2xl">待报到患者</h2><p className="text-sm text-[#a4c5bc]">请按预约时间报到</p></div>{smallList(waiting, "当前暂无待报到患者。")}</section>{!full && <div className="mt-6 text-center"><Link href="/"><Button variant="ghost" className="text-[#a9c8c0] hover:bg-white/10 hover:text-white">返回工作台</Button></Link></div>}</div>;
}
