import QrScanner from "@/components/QrScanner";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Clock3, RefreshCw, Stethoscope } from "lucide-react";
import { useState } from "react";

export default function KioskPage() {
  const [payload, setPayload] = useState(""); const inspect = trpc.kiosk.inspect.useQuery({ payload }, { enabled: Boolean(payload), retry: false }); const checkIn = trpc.kiosk.checkIn.useMutation();
  const reset = () => { setPayload(""); checkIn.reset(); };
  return <div className="min-h-screen bg-[#103f3e] px-5 py-8 text-white clinic-grid"><div className="mx-auto max-w-3xl"><div className="flex items-center justify-center gap-3 text-[#d0a85e]"><span className="h-10 w-10 rounded-2xl bg-[#d0a85e] grid place-items-center"><Stethoscope className="h-5 w-5 text-[#103f3e]" /></span><span className="tracking-[0.15em] text-sm">PAIN CARE SELF CHECK-IN</span></div><h1 className="mt-10 text-center text-4xl sm:text-5xl font-serif">患者自助报到</h1><p className="mt-4 text-center text-[#b5d2ca]">请将患者二维码放入扫描框内，或使用扫码枪完成报到。</p><Card className="mt-10 rounded-[2rem] border-white/10 bg-white text-[#1a4340] shadow-2xl"><CardContent className="p-6 sm:p-10">{!checkIn.data ? <><QrScanner label="请扫描患者二维码" onResult={setPayload} autoStart />{inspect.isFetching && <p className="mt-6 text-center text-sm text-[#6c827c]">正在读取今日排班…</p>}{inspect.data?.found === false && <p className="mt-6 rounded-xl bg-[#faece8] p-4 text-center text-sm text-[#a6534b]">未识别到有效患者二维码，请联系前台工作人员。</p>}{inspect.data?.found && <div className="mt-6 rounded-2xl bg-[#eef7f2] p-5 text-center"><p className="font-serif text-2xl">您好，{inspect.data.patient.fullName}</p>{inspect.data.schedule ? <><p className="mt-3 text-[#54736a]">今日治疗：{inspect.data.schedule.projectName}</p><p className="mt-1 text-sm text-[#778d86]">预约时间 {inspect.data.schedule.scheduledAt.toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })}</p><Button className="mt-5 w-full h-12 rounded-xl bg-[#0e5a55] hover:bg-[#084842]" onClick={() => checkIn.mutate({ payload })} disabled={checkIn.isPending}>{checkIn.isPending ? "正在报到…" : "确认今日报到"}</Button></> : <p className="mt-4 text-sm text-[#8d5e21]">您今日暂无待治疗排班，请联系前台工作人员。</p>}</div>}</> : <div className="py-12 text-center"><span className="mx-auto h-16 w-16 rounded-full bg-[#ddf0e7] grid place-items-center"><CheckCircle2 className="h-9 w-9 text-[#137264]" /></span><h2 className="mt-6 text-3xl font-serif">报到成功</h2><p className="mt-3 text-[#5f7b71]">{checkIn.data.fullName}，请在候诊区等候叫号。</p><div className="mt-4 flex justify-center gap-2 text-sm text-[#637d74]"><Clock3 className="h-4 w-4" />{checkIn.data.projectName} · {checkIn.data.scheduledAt.toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })}</div><Button variant="outline" className="mt-9 rounded-xl" onClick={reset}><RefreshCw className="h-4 w-4" />下一位患者</Button></div>}</CardContent></Card></div></div>;
}

